### ISSUE TITLE
Income desync issue

### ISSUE THREAD

**Issue by johnabaker** [CitiesSkylinesMultiplayer/CSM#100]
Hi,

Firstly, thanks for all the effort getting this mod to how it is. Very well done.

I tested this with a friend last night and everything works as expected for 15 minutes then my friend suddenly reports 0 income. Everything else continues to work fine.

Any thoughts on what could be the issue.

Many thanks.

**Comment by Orkan-M** [comment]
To add to this, when another client takes a loan, the server doesn't take it as well, but money is still added. The incomes are synced, until the point where the other client has interest applied to their weekly income, thus leading to different incomes, and the server never gets interest, with free money. The server player then reloads the save, and it's as if money came from nowhere for free without any problems, but a single reload of the game.
