### ISSUE TITLE
Placing Coal Power causes Desync

### ISSUE THREAD

**Issue by TJPlaysNow** [CitiesSkylinesMultiplayer/CSM#108]
**Describe the bug**
When the client places the coal power plant only the base appears for the host, and it does not make power for the city.

**To Reproduce**
1. Have the client place a coal power plant.

**Comment by kaenganxt** [comment]
Please check if this issue is fixed in the newest development version.

**Comment by kaenganxt** [comment]
Closing this as the issue should be fixed.
