### ISSUE TITLE
Can't Pause

### ISSUE THREAD

**Issue by Treholt3103** [CitiesSkylinesMultiplayer/CSM#11]
First of all thanks for an amazing work, this really has enormous potential.

I just did a test over LAN. The sync of speed works as it should (Really impressive) but it can't handle Pause.

**Comment by DominicMaas** [comment]
Yeah, I got stuck on that when I was last working on the mod. Could not figure out how to change it.

I cannot remember the reason why, but I think the network loop also stopped when the simulation was paused (so no data was sent), but I may be wrong. I'll have to take another look sometime.

**Comment by Treholt3103** [comment]
It took 2,5 month i had to learn to code C# and use 10's of hours reviewing your code, but i solved the problem.

The problem is that when you use the same command to send both the pause and the speed message, it will first pause and then instantly start again, by splitting the commands in a speed and a pause message, it works (i will try to upload my solution but i'm totally new at this so we will see how it goes)

**Comment by DominicMaas** [comment]
Thanks, It seems to look good (I'll take a look later this week and merge the pull request), I've got a test on Tuesday and Thursday that I have to focus on at the moment.
