### ISSUE TITLE
Is there a Roadmap?

### ISSUE THREAD

**Issue by Smeagol001** [CitiesSkylinesMultiplayer/CSM#112]

**Comment by brettpenzer123** [comment]
You could refer to [here](https://github.com/DominicMaas/Tango/projects/1) but it hasn't been updated in a while and majority of us that have contributed to the project are currently studying. 

I would recommend joining the [discord server](https://discordapp.com/invite/RjACPhd) if you haven't already as we continually post on there.

I'll resume looking at some of the issues when I've finished studying completely in the next two weeks.

**Comment by kaenganxt** [comment]
Now there is :) See #152
