### ISSUE TITLE
Syncing issues, while playing with two players.

### ISSUE THREAD

**Issue by matteo-mlr** [CitiesSkylinesMultiplayer/CSM#116]
Hi there, thank you for this great mod!
I just started using it but noticed a problem, where me and my teammate don't have the same date and therefore also not the same population in game, so we basically have two very different games running. The one person is already allowed to build a specific building and the other one is not. Is there a way to fix this issue?

Best regards
Matteo Mueller

**Comment by brettpenzer123** [comment]
Hi @matteo-mlr. I would suggest that you join the discord server: https://discordapp.com/invite/RjACPhd as these issues you have mentioned above are on our list to fix or to implement if they do not already exist. It would be a good way to keep up with what is being added to the mod.

**Comment by kaenganxt** [comment]
Closing this as the problems depend on many factors already covered in other issues. The problems are mostly caused because certain features are not yet implemented. (Still thanks for your report)
