### ISSUE TITLE
Connected, but not getting roads, money, etc

### ISSUE THREAD

**Issue by Sander0542** [CitiesSkylinesMultiplayer/CSM#12]
Hi,

I installed this mod on my 2 systems, but when I connect them. It gives a green text saying connected, but when I place roads they are not visible on the other game. Why does this happen?

I am using a local direct IP connection

**Comment by Treholt3103** [comment]
Im taking the liberty of answering.
The mod is still in early development and does not yet sync, roads money ect. The only thing it should be able to sync is the game speed.

**Comment by Sander0542** [comment]
Oh okay, sorry

With game speed, you mean the time?

**Comment by Treholt3103** [comment]
yes however the Pause button does not work yet

**Comment by akposton** [comment]
Update:
Money syncs right away between games (this was done with host on new game, client loaded saved game)
Host Computer builds roads, wind turbine, and powerlines
Client Computer sees wind turbine, but no powerlines, but sees buildings appear
Client Computer places wind turbines and host computer sees those appear

**Comment by DominicMaas** [comment]
I'll close this issue in favour of the separate issues discussing different aspects of syncing.
