### ISSUE TITLE
Following the manual build instructions returns a missing 0Harmony.dll error when running the script

### ISSUE THREAD

**Issue by kinlochuk** [CitiesSkylinesMultiplayer/CSM#142]
_Note: I already reported this issue on the discord, but I added it here as well to help keep track of it, (and because I had already half typed this out and didn't want to waste all that typing)_
This is an issue with the manual building process, mostly likely the build script.
When following the instructions at the [Developer Resources](https://github.com/DominicMaas/Tango/wiki/Developer-Resources) to manually build the project the following script is used: 
`.\build.ps1 -Update -Build -Install`
However this script fails with a **_lot_** of errors regarding a missing 0Harmony.dll

**To Reproduce**
1. Clone a fresh version of the project
2. Follow these instructions from the developer resources page:
a. Open the scripts folder.
b. Run the following command in powershell .\build.ps1 -Update -Build -Install. 
3. Watch as a wall of errors fills your vision and the script completely fails.

**Expected behavior**
Not receiving a wall of errors, or more generally, the script working as advertised by the Developer Resources instructions list for manual building/installing.

**Additional context**

Seems to be caused by the -update flag section of the build script deleting then recreating the assemblies folder, but loosing the 0Harmony.dll in the process.
A workaround is to copy the 0Harmony.dll out of the assemblies folder before running the script with the -update flag, then copying it back in afterwards and re-running the build script without the -update flag.
(or you could automate it by modifying the build script to do all that moving automatically, but that requires tweaking the build.ps script).

**Comment by DominicMaas** [comment]
Good catch, I was meaning to take a look into the script after we decided to bundle the 0Harmony dll, but I completely forgot about it.

**Comment by kaenganxt** [comment]
Fixed by https://github.com/DominicMaas/Tango/commit/af1582cdb3d035efeaed3f2254a5694a398c6c66
