### ISSUE TITLE
Deactivate building not synced

### ISSUE THREAD

**Issue by fred-cardoso** [CitiesSkylinesMultiplayer/CSM#145]
When the host deactivates a building, the client building remains active.

1. Place a Wind Turbine
2. Deactivate the Turbine in host side
3. Check client side for a still active Turbine

It should deactivate the turbine in the clients as well.

**Comment by kaenganxt** [comment]
I'm currently working on syncing many building settings, so this feature will be part of my next commit.

**Comment by fred-cardoso** [comment]
Thanks @kaenganxt By the way, great mod :-D
