### ISSUE TITLE
Better Handling of Timeouts

### ISSUE THREAD

**Issue by shotwn** [CitiesSkylinesMultiplayer/CSM#149]
**Is your feature request related to a problem? Please describe.**
My friend has a bad adsl connection. Which causes a lot of timeouts but handling them is non existing and experience breaking.

**Describe the solution you'd like**
1. After timeout warn both client and server in a more serious manner.
- Maybe prevent them from further building to prevent desync. There can be a dismissable warning which disappears automatically on reconnect.
- Or cache changes for a limited period for both client and host. (like 3 minutes) And in reconnect apply the changes chronologically.

2. Maybe create an option to allow saving every sync message on host with an incremental ID, these can get saved to a file from RAM in certain intervals. When a client rejoins ask for last received sync message ID then send the sync messages after that ID.
- Meanwhile don't allow client to do it's own changes to send to server. Or cache client changes also.
- There can be a limit on cache. If last sync point + 1 is not available on the host anymore a warning for a manual save file transfer can be prompted.
- Of course this means the mod has to be initiated once the save file used in multiplayer is initiated to start caching changes. Which means saves used in multiplayer should also be identified between sessions. Or once the save is loaded, mod should ask if save will be used in multiplayer for that session.

I didn't find my way around the source yet but I feel like one of these are not impossible to implement.

I've found message serialization and connection initiation points, and caching seems possible if the game allows for permanent data storage. 

Although, my C# is so rusty just to catch up would take an insane amount of time. Let alone implement this.

**Comment by kaenganxt** [comment]
Timeouts are already handled for a long time now. #309 implemented better timeout handling during save downloading and game loading.
If this is still a problem, please reopen this issue.
