### ISSUE TITLE
PlayerLocationCommand Improvements

### ISSUE THREAD

**Issue by DominicMaas** [CitiesSkylinesMultiplayer/CSM#155]
- Limit how often the `PlayerLocationCommand` is sent, or look into how the command is being handled on the server / other clients. Are there any bottlenecks that could be fixed? (I may introduce a timing library so we can see if there are any areas of the mod that need improvements).
- Fix `ICameraUpdateCurrentPosition.PostFix` (`ICameraHandler.cs`). It's causing a whole lot of exceptions (on the host, have not tested the client).

![image](https://user-images.githubusercontent.com/5589453/71327529-8f5ba680-256e-11ea-81b6-5d14572f5b9b.png)

Related to #153

**Comment by DominicMaas** [comment]
The actual sending and receiving of `PlayerLocationCommand` might not be causing the issue, but instead the size of the log file due to how often the command is sent.

**Comment by DominicMaas** [comment]
`Tag: P is not defined` is caused when the client moves
`NullRefException` is caused when the host moves

**Comment by kaenganxt** [comment]
PlayerLocationCommand has been replaced by the new player pointer implementation
