### ISSUE TITLE
Feature: Add in support for the Syncing of TM:PE Road Rules

### ISSUE THREAD

**Issue by LRTNZ** [CitiesSkylinesMultiplayer/CSM#181]
## Problem to Solve

Traffic in Cities: Skylines. Specifically the AI. We all know it, and I am pretty sure we all hate it.
When playing in multiplayer, this doesn't change in the slightest.
What would be nice would be if there was a way to deal to it in multiplayer, like you can in single player with TM:PE

## Potential Solution

Developing a way to support the syncing of the Traffic Manager, Presidential Edition "Road Rules" between the clients. As things such as the road settings are already being synchronised, this is not a strange concept for this mod, it is just expanding on the ruleset for the roads that is synced. 

Like how traffic lights and stop signs are synced in the base game, being able to sync Traffic Manger would be great! At this point, I would even settle for a basic one that can support the lane connectors to be able to help relieve the inane merging the "AI" likes to do. Which is otherwise best described as:
```
if(willMergeCauseTrafficNightmare == true){
   doMergeAndCauseHell();
} else {
   useSpaghettiMadeToTryStopHell();
}
```
## Alternatives Considered

- Petition Paradox to fix their buggy traffic AI
- Live with it, and the horrid mess it causes
- Check to see if the mod was already supported by this plugin

## Additional Context

Nothing, other than to say my mates and I love the mod, and have had many hours of fun with it, and the social aspect it brings to the game. The fact that a community driven mod brings better multiplayer support to a Paradox game than they can official provide (Looking at you Prison Architect Multiplayer) is wonderful!

**Comment by joaogl** [comment]
I guess this one could be closed since we have https://github.com/CitiesSkylinesMultiplayer/CSM/issues/235 moving no?

**Comment by LRTNZ** [comment]
If people are confident that that will solve this issue, I don't see why not.

**Comment by kaenganxt** [comment]
Continued in #289
