### ISSUE TITLE
Area Zoning De-syncing

### ISSUE THREAD

**Issue by kjnars** [CitiesSkylinesMultiplayer/CSM#187]
Lately I've been experiencing more desyncing of the zones. My side would be zoned, but the connected client is shown as a non-zoned area. 
The buildings build up then right away demolished by themselves. We would have to do complete game restart just to fix it for a little bit. I'm guessing that the mod is fighting between the two clients and doesn't know what to zone/keep/build.
The /sync doesn't seem to fix the zoning issues for now on our game. Both sides have the same exact dlc, etc.

Edit: Closed due to issue already posted [#172](https://github.com/CitiesSkylinesMultiplayer/CSM/issues/172)

**Comment by DominicMaas** [comment]
Duplicate of #172 (just to link things up in GitHub so we can reference this issue later)
