### ISSUE TITLE
Where to Download?

### ISSUE THREAD

**Issue by Sander0542** [CitiesSkylinesMultiplayer/CSM#19]
I clicked the "here" link in README.md, next I clicked on the latest build, but I can not find the ZIP download. Where do I need to click?

![image](https://user-images.githubusercontent.com/11409610/47265890-240fe200-d52f-11e8-802f-b5396042c09d.png)

**Comment by minestarnl** [comment]
I couldn't find it either

**Comment by Treholt3103** [comment]
Yeah i can't get it to work either, but you should still be able download the zip from github and compile it :)

**Comment by DominicMaas** [comment]
Oh, it appears that the download link does not appear for public users. I'll take a look into it.
