### ISSUE TITLE
Add a player list

### ISSUE THREAD

**Issue by kaenganxt** [CitiesSkylinesMultiplayer/CSM#197]
### Description
All players should be able to see a list of connected players. The host should be able to kick players from the server.

### Implementation hints
- Add a panel (see other panels in the Panels folder) containing the list of players (`MultiplayerManager.Instance.PlayerList`)
- Add buttons to open the panel in the ConnectionPanel
- Add buttons to kick a player in the panel (only on the host)
- When clicked, the player should be disconnected (see ConnectedPlayers dict in Server.cs, Player.NetPeer.Disconnect())

Note: This is an issue suited for the Hacktoberfest (see https://hacktoberfest.digitalocean.com/), feel free to ask questions here or on Discord (https://discord.gg/RjACPhd).

**Comment by elitenudel** [comment]
I will be giving this one a try.

**Comment by elitenudel** [comment]
See https://github.com/CitiesSkylinesMultiplayer/CSM/pull/207

**Comment by kaenganxt** [comment]
Implemented in #207
