### ISSUE TITLE
Add player click indicator

### ISSUE THREAD

**Issue by kaenganxt** [CitiesSkylinesMultiplayer/CSM#198]
### Description
When clicking on the map, all other players should see an indicator at the clicked location. This should make it easier to share certain spots on the map.

### Implementation hints
- Investigate how to track mouse clicks in Cities: Skylines or Unity in general
- Investigate how to display shapes in the game world.
- Create a new command in Commands/Data/Game and a handler in Commands/Data/Game
- When a click occurs, send the new command to all other players
- In the command handler, display the shape for a certain time span in the world

Note: This is an issue suited for the Hacktoberfest (see https://hacktoberfest.digitalocean.com/), feel free to ask questions here or on Discord (https://discord.gg/RjACPhd).

**Comment by dfrankes** [comment]
This would be a great addition to the PlayerLocationHandler. I think I'll start working on this one.

**Comment by CWMlolzlz** [comment]
@kaenganxt 
Is this still under any active development?
I have pulled the source code and have managed to get some the BuildingTool and NetTool syncing between clients.
I am more than happy to see this through for other tools.

This would be a massive improvement to the multiplayer experience and I would love to contribute in some way.

**Comment by kaenganxt** [comment]
I don't think that anyone is currently working on this. I would love to see this implemented.
Feel free to open a draft PR so we can discuss your changes.

**Comment by kaenganxt** [comment]
Implemented by #274
