### ISSUE TITLE
Improve chat

### ISSUE THREAD

**Issue by kaenganxt** [CitiesSkylinesMultiplayer/CSM#199]
### Description
The chat should be more transparent or invisible when inactive. When a message arrives, the chat should be become clearly visible. It should also become visible when clicking on the input bar.

### Implementation hints
- All chat panel related code is contained in Panels/ChatLogPanel.cs
- The documentation of the ColossalFramework UI API may give some additional hints: https://skylines.paradoxwikis.com/UI_Framework

Note: This is an issue suited for the Hacktoberfest (see https://hacktoberfest.digitalocean.com/), feel free to ask questions here or on Discord (https://discord.gg/RjACPhd).

**Comment by lgoenner** [comment]
Currently giving this a try.
@kaenganxt since Hacktoberfest is now [opt-in](https://github.com/digitalocean/hacktoberfest/pull/596), can you add hacktoberfest as a repository topic?

**Comment by kaenganxt** [comment]
Added the topic, thanks for letting me know.
