### ISSUE TITLE
Joining a game

### ISSUE THREAD

**Issue by Callum-Bell** [CitiesSkylinesMultiplayer/CSM#2]
I will be hosting the game, and i see it says a port is required. Does it matter what port i use, could i just use the default steam port 34197 or do i need to do something else?

**Comment by DominicMaas** [comment]
Be default the server runs on port 4230. This value is not exposed in the UI - I'll work on that shortly.

**Comment by Callum-Bell** [comment]
So to be clear, all i need to do. Is "Press host game" and send my public ip with the port 4230 (forwarded). No server configs i need to edit?


Also, i have, right clicked the project and press "build" because i couldnt figure out how to build it correctly, could you upload the actual mod files, as i cannot enter a port or ip

Thanks for the help!
