### ISSUE TITLE
Add automatic chat closing

### ISSUE THREAD

**Issue by kaenganxt** [CitiesSkylinesMultiplayer/CSM#201]
### Description
In addition to the chat improvements made in #200 the chat should auto-close after a few seconds (e.g. 5 seconds).

### Implementation hints
- All chat panel related code is contained in Panels/ChatLogPanel.cs

Note: This is an issue suited for the Hacktoberfest (see https://hacktoberfest.digitalocean.com/), feel free to ask questions here or on Discord (https://discord.gg/RjACPhd).

**Comment by ollelogdahl** [comment]
Hello. I would like to contribute to this. Am i to be assigned, or should i send a pr?

**Comment by kaenganxt** [comment]
Feel free to try this and just send a pr.
Your comment should be enough that others see that someone is working on it :)
