### ISSUE TITLE
TM:PE seems to be incompatible with NLog

### ISSUE THREAD

**Issue by lgoenner** [CitiesSkylinesMultiplayer/CSM#204]
Simply launching TMPE and CSM together results in this error:

![image](https://user-images.githubusercontent.com/14999635/95771579-98636300-0cbb-11eb-826f-15793fe79da8.png)

`Warning 15.9578899: Could not load global config: System.TypeLoadException: Could not load type 'System.Xml.Serialization.XmlRootAttribute' from assembly 'System.Xml, Version=2.0.0.0, ...`

I am using [the latest CI version](https://ci.appveyor.com/project/krzychu124/tmpe/branch/master/artifacts), since https://github.com/CitiesSkylinesMods/TMPE/pull/866 is not contained in any releases.

I have no idea why this is happening, but removing NLog fixes the problem.

**Comment by MightyWizard** [comment]
NLog FileTarget causes errors when other mods such as TMPE try to load XML, causing TMPE to fail to load user config. 
The exact piece of code causing the errors is below from file CSM.Util.Log.cs
`
FileTarget logfile = new FileTarget("logfile")
{
      FileName = "multiplayer-logs/log-current.txt",
      ArchiveFileName = "multiplayer-logs/log-${shortdate}.txt",
      Layout = layout,
      ArchiveEvery = FileArchivePeriod.Day,
      MaxArchiveFiles = 7,
      ConcurrentWrites = true,
};
`

**Comment by MightyWizard** [comment]
If you comment that out the error goes away. 

Looking into it I think the best option is to copy and adapt the implementation that TMPE uses for their logging shown here.
A simple custom written logging method
https://github.com/CitiesSkylinesMods/TMPE/blob/master/TLM/CSUtil.Commons/Log.cs

The centralized logging you have done will make this change very easy to do, just updating the single log class
