### ISSUE TITLE
Chirper for Communication

### ISSUE THREAD

**Issue by XxSlowMOxX** [CitiesSkylinesMultiplayer/CSM#209]
Right now i am not happy with the Chirper in C:S. 
To give it some use i propose that the Chirper could show Players Joining / Leaving, and / or Chat Messages from other Players.

This is probably not that hard to acomplish, as the IChirper Interface probably allows adding of new Messages.

I will look into this myself, but this is my first Project of this Sort, and so i will submit this Feature Request so that others can join the Struggle to make that Bird useful.

**Comment by XxSlowMOxX** [comment]
Ok, it seems asthough just adding the Message to the Chirper Panel within the appropriate Handler (ChatMessageHandler, etc. ) is the fastest method.

`ChirpPanel chirpPane;
chirpPane = GameObject.Find("ChirperPanel").GetComponent<ChirpPanel>();
            chirpPane.AddMessage(new ChirpMess(0, playerName, text));`

**Comment by RvNovae** [comment]
Seems to work rather well. Thanks for the great documentation on the issue!

I'll revisit this in a few days to finish it up.
