### ISSUE TITLE
Issue between Epic Games and Steam version?

### ISSUE THREAD

**Issue by GreenOctagon** [CitiesSkylinesMultiplayer/CSM#210]
Everything has been set up properly, but our versions show the same patch number except for the epicgames one has -e12 at the end.

**Active DLCs**
No active DLC

**Active mods**
Only Multiplayer

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 2008.44
- Game version: 1.13.2-f1-e12

**Comment by ghost** [comment]
Can reproduce. My Steam version is the 1.13-f1 but my friend's Epic version is the one as listed above

**Comment by GreenOctagon** [comment]
Potential work-around by owning it on both platforms and moving steam files to epic games folder and verifying files through the epic launcher. This fix deletes saves and steam worskshop items, but it syncs versions to the -e12 version.
