### ISSUE TITLE
Unable to open chat after it closes

### ISSUE THREAD

**Issue by LepaBrenaa** [CitiesSkylinesMultiplayer/CSM#216]
**Describe the bug**
After the chat closes down, I am unable to open it back again.
I tried every button on my keyboard, and it hadn't worked.

**Active DLCs**
All DLC'S disabled.

**Active mods**
Only this one (CSM)

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: CSM 2012.76
- Game version: latest Steam version (5.6.7.3267)

**Comment by Revilum** [comment]
type + and it should open again

**Comment by LepaBrenaa** [comment]
> type + and it should open again

I tried that, and it does nothing unfortunately.

EDIT: T worked for oppening and closing the chat.
