### ISSUE TITLE
Close multiplayer menu with ESC

### ISSUE THREAD

**Issue by Bluenix2** [CitiesSkylinesMultiplayer/CSM#223]
## Summary
When pressing ESC, instead of closing the menu, you open the pause menu. This is somewhat unexpected.

Additionally I think the Multiplayer menu should either be duplicated or completely moved to the pause screen. Makes much more sense having it there.
At least the Host Game button.

**Comment by addidotlol** [comment]
I agree with the Multiplayer menu being moved. The multiplayer menu in the top left is a bit of an eyesore.
