### ISSUE TITLE
Verify commands list on wiki

### ISSUE THREAD

**Issue by Bluenix2** [CitiesSkylinesMultiplayer/CSM#224]
In short, the commands list on the wiki doesn't seem up-to-date. As an example, the `/sync` command is not listed. Yet it's quite often referenced in the Discord server as a good way to sync your saves.

**Comment by ghpdohmen** [comment]
I should have just fixed this. Seems like only the sync chat command was missing.

**Comment by kaenganxt** [comment]
Thanks
