### ISSUE TITLE
Chat command shortcut

### ISSUE THREAD

**Issue by Bluenix2** [CitiesSkylinesMultiplayer/CSM#225]
Similar to how the chat works in Minecraft, if you type `/` it should display the chat with that character typed and the chat selected ready for input.

Similar to that, I haven't tested, but if you press T it only toggles viewing the chat right? Pressing T should make the chat selected and ready for input.

**Comment by RvNovae** [comment]
I'm not sure if I understand the issue correctly, but when I press `T` the chat windows opens and is ready to accept input.
Is this issue specifically requesting `/` to be added?

**Comment by Bluenix2** [comment]
> but when I press T the chat windows opens and is ready to accept input.

Yes, I was able to test this and it does. I wasn't sure if it did that when opening this issue.

> Is this issue specifically requesting / to be added?

Exactly, it would open the chat with `/` already typed. So a shortcut for `T` + `/`.

**Comment by RvNovae** [comment]
Got it, thanks for the clarification!
