### ISSUE TITLE
Me & Friend cannot pause / unpause  or speed up the game

### ISSUE THREAD

**Issue by AlfieTheAlpha** [CitiesSkylinesMultiplayer/CSM#226]
after a minute of starting a new world, we cannot pause/ unpause or even speedup the game

**Comment by jerrikf** [comment]
Same for me! Would be really nice if this could be fixed soon! :)

**Comment by RoosterBooster007** [comment]
Same, it's random for me... Any news of when/if this going to be fixed?

**Comment by Xtortion** [comment]
Same here, even as the host I can't even pause at times and even when I can it won't pause the client. It gets things horribly out of sync this way unfortunately.

**Comment by addidotlol** [comment]
this happens at random for me.

**Comment by kaenganxt** [comment]
Does anyone have a way of reproducing this? Does it happen more often on a specific save game? If yes, could someone attach such a save game please?

**Comment by AlfieTheAlpha** [comment]
The issue randomly disappeared for me

**Comment by addidotlol** [comment]
> 
> 
> Does anyone have a way of reproducing this? Does it happen more often on a specific save game? If yes, could someone attach such a save game please?

it happens at random, about 5-15 minutes after starting the multiplayer session.

**Comment by kaenganxt** [comment]
Please test if the current development version fixes the speed/pause issues. You can download the version at the bottom of the following page: https://github.com/CitiesSkylinesMultiplayer/CSM/actions/runs/552590913
Extract the zip file and run the included install script in powershell to install the mod.
