### ISSUE TITLE
Power lines and water pipes not syncing

### ISSUE THREAD

**Issue by Treholt3103** [CitiesSkylinesMultiplayer/CSM#23]
When creating power lines, only the "towers" and not the wire is created on the receiving Client/Server.

**Comment by Treholt3103** [comment]
Related to this water pipes are not syncing either. I believe its because of how the game handles these. I think they are 'half' buildings 'half' "roads"(net). and since we are not yet syncing the data held by the NetManager these bugs appears.

**Comment by DurtyFree** [comment]
We are speaking about so called game "Net" entities, there are NetNodes and NetSegments.
Some buildings consist of a Building and a NetNode. Multiple NetNode connect up via NetSegments.

NetSegments & NetNodes need to be synced in order to fix those issues.
