### ISSUE TITLE
Move it and other stuff

### ISSUE THREAD

**Issue by KuprumLight** [CitiesSkylinesMultiplayer/CSM#234]
Know that mods  **are not supported**  yet, but maybe author want to know...
Main problem is synchronization with Move it. When we have successful connected clients, and try to move any object using mod there would be no errors or crashes or smth. else,  BUT when one player moves something using the mod, another player doesn't see the changes. Here some details, imagine that you placed windmill away from your city (they are not connected), then if you use move it to place the windmill near the buildings on your screen everything would  be fine and the problems will be solved, BUT another player sees that there are no problems with electricity but the windmill still stays away from the city, and has no connection.
maybe the command /sync can fix it, but anyway, using this command after every transformation is painfull.

**Comment by kaenganxt** [comment]
I'm closing this issue since it's currently not a goal of this mod to support other mods. I'll open a tracking issue for mod support later.
