### ISSUE TITLE
Move command logic into commands.

### ISSUE THREAD

**Issue by DominicMaas** [CitiesSkylinesMultiplayer/CSM#24]
At the moment command logic is stored within the Server or Client classes (depending on what it does). This works currently, but will be unsustainable as more and more commands are added.

I'm adding this here to remind my self later.

* Add two virtual methods to the base command, one for server side logic and the other for client logic.
* Move current logic into these virtual methods.
* Change server and client classes to auto call these methods.

**Comment by kaenganxt** [comment]
Are you already working on this or can I have a try?
