### ISSUE TITLE
Display changelog when mod updates

### ISSUE THREAD

**Issue by DominicMaas** [CitiesSkylinesMultiplayer/CSM#246]
To improve the user experience, when the mod updates (checking a stored mod version in a text file maybe?), we should display a changelog stating what's new in that version of the mod.

This will be particularly useful for "breaking changes" that affect how the game worked before (like the multiplayer menu moving to the main menu), or new features (chat in chirper).

**Comment by kaenganxt** [comment]
I actually had the same idea and started doing this already :)
