### ISSUE TITLE
Can I use with cities skyline Windows 10 edition

### ISSUE THREAD

**Issue by Teayear0** [CitiesSkylinesMultiplayer/CSM#255]
Can I use with cities skyline Windows 10 edition

**Comment by xADDBx** [comment]
As far as I can tell from the documentation (specifically the [FAQ](https://github.com/CitiesSkylinesMultiplayer/CSM/wiki/Frequently-Asked-Questions) and looking into the build script, this mod supports Cities Skyline on Windows, OSX and Linux as long as Microsoft Visual Studio 2019 or 2017 or 2015 is installed. So yes, you should be able to use it.

**Comment by Revilum** [comment]
it is not possible to use this mod with the windows 10 edition of the game because the windows 10 edition is just the Xbox version which haa no mod support
