### ISSUE TITLE
Connection Screen

### ISSUE THREAD

**Issue by Callum-Bell** [CitiesSkylinesMultiplayer/CSM#3]
Im not too sure if this mod is completely concept. But i cannot type anything in the multiplayer connect screen
Also im not sure if i built it right. I just right clicked and built it, as when i tried your way, i couldnt find a button to build it.

Thanks, Again...

**Comment by DominicMaas** [comment]
It's mostly concept at the moment. Currently you can host a server (default settings) and connect to a server (entering an IP and Port).

I added more info to the multiplayer connect screen the other day (so you will have to build the latest changes).

You can find installation instructions on the wiki here (I'll update them to make more sense): https://github.com/DominicMaas/Tango/wiki

**Comment by Callum-Bell** [comment]
Thanks i will give it a go
