### ISSUE TITLE
Grey UI box on the left side blocking some functions

### ISSUE THREAD

**Issue by Treholt3103** [CitiesSkylinesMultiplayer/CSM#30]
The new grey UI box on the lower left side is blocking some of the game functions, e.g the first tab in the economy overview tool :)

**Comment by DominicMaas** [comment]
Thanks for pointing that out! I'll work on it shortly (will also make it draggable).

**Comment by DominicMaas** [comment]
"shortly" :D I've extended some chat functionality, including hiding (with the "~" key, or by typing "/hide"). The "~" will also show a hidden chat.

**Comment by andsim** [comment]
it still block bottom left  screen for mouse function and other one in menu of economy windows when in hide
