### ISSUE TITLE
Roads not syncing up

### ISSUE THREAD

**Issue by junkmail88** [CitiesSkylinesMultiplayer/CSM#31]
A friend and I connected to each other.
We can't see any roads the other person built, but money and building sync up fine.

**Comment by DominicMaas** [comment]
Road syncing is not implemented yet. But that's probably the next major thing that will be worked on.

**Comment by MisterX2000** [comment]
Roads do sync now, but upgrading or demolishing roads doesn't sync.

**Comment by Treholt3103** [comment]
Only creation of roads has been implementet, the rest still needs some coding :)

**Comment by DominicMaas** [comment]
What's the status of this issue now? @junkmail88 are you still having any issues with road syncing?
