### ISSUE TITLE
Building Road Sync

### ISSUE THREAD

**Issue by Treholt3103** [CitiesSkylinesMultiplayer/CSM#36]
The ICities.dll does not contain an extension for handling roads, as it does for buildings (where it can run an extension each time a building is created or destroyed) so we need a cleaver solution to overcome that problem.

**Comment by Treholt3103** [comment]
Update:
I have successfully synced NetNode and NetNodeSegments, (and send both a road and a waterpipe from server to client) there are still some things to be worked out, but there has been a substantial progress in syncing these.

**Comment by DominicMaas** [comment]
That's awesome to hear, thanks a lot!

**Comment by akasoggybunz** [comment]
That is awesome! I am looking forward to these features being implemented! 

Do those NetNodes and NetNodeSegments include Power Lines? I noticed that Power Lines don't sync to Client as well. Obviously not as big of a deal as roads and water pipes. Again, bravo!

**Comment by Treholt3103** [comment]
It contains Roads Waterpipes, Powerlines ect, the update has just been Pushed and is pending merger :)
