### ISSUE TITLE
The host can't have the name "host"

### ISSUE THREAD

**Issue by MisterX2000** [CitiesSkylinesMultiplayer/CSM#41]
When you host a game and enter as the host name `host`, this error gets displayed:
`An element with the same key already exists in the dictionary. [System.ArgumentException]`

**Comment by MisterX2000** [comment]
I've just tested this again and it seems to be fixed, or it was a problem on my end.

**Comment by DominicMaas** [comment]
It's possible that it was fixed in one of the prior commits. If you encounter the issue again, feel free to re-open this issue.
