### ISSUE TITLE
Only one person can connect at once.

### ISSUE THREAD

**Issue by Drezzz** [CitiesSkylinesMultiplayer/CSM#43]
Hey man. I'm super new to city skylines but I'm really interested in getting into it with 2 of my friends. Right now we can only get 1 person to connect to the host at a time. Is that working as intended or is something going wrong? 

Also, you mentioned you wanted to make it easy to run. I highly recommend just sharing your mod on the steam workshop. You can literally just press the "share" button in the mod list in city skylines. That way people can just subscribe to it and it just works for them. I posted your mod already to share with my friend who was having trouble with installing through powershell, I can take it down if you want to make your own posting. It's super easy to update it and stuff and to install it people just have to press subscribe and it gets added to their mod files! I highly recommend looking into it!

Workshop link: https://steamcommunity.com/sharedfiles/filedetails/?id=1556336761

**Comment by DominicMaas** [comment]
I've heard from someone else about the two person limit. This shouldn't be the case (nothing in the mod is preventing more than two people connecting).

What happens when another person tries to connect to the host? Do they get an error message? Does it do nothing? Will help me narrow down the bug.

Steam Workshop was originally planned for later on when the mod is in a more usable state, I'll take a look into the Steam Workshop process and see if I can automate builds from this repo to appear in the workshop.

You shouldn't need to use the script to install the mod, you can just extract the downloaded files to the mentioned folder (under the readme file). But I will take a look into Steam Workshop support.

**Comment by Drezzz** [comment]
It just does nothing @DominicMaas. We just sit there trying to connect until it times out I guess. Also, it doesn't currently sync newly built stuff right? Like if you connect to someones city they worked on since you last were it doesn't update? @Treholt3103 Our solution to that problem right now is just to pause the timer on the host side and send the save file to the people joining then join with that file and resume. 

So basically, I'm not a CS person AT ALL (I do mechanical) and my friend (who is a CS person) was literally screen sharing with me to walk me through this stuff. We ended up figuring out that the read me archive in your azure account thing was what we were supposed to use. It worked for me first try and I got in. As I'm waiting for my friend, he's like "IVE BEEN BAMBOOZLED." It just didn't work for him. I was looking at the mods folder and there was a share button and I was like "I wonder..." and it just worked LOL. It was actually so easy.

**Comment by Treholt3103** [comment]
If you both start from the same savegame, and connect before things changes (before any new buildings are build/removed, roads constructet ect) you should be in sync.
The important thing is to start from the exact same savegame file, so you have to share the savegame file before starting :)

**Comment by DominicMaas** [comment]
So it times out? Hmmm. I'll do some testing this afternoon, there might be a setting that I have to change to allow multiple connections.

As you discovered, you have to start with the same saved game. Ideally the game should be auto paused on connect, the save game file copied, sent over to the client, and the client loads the game (then resume). 

There's a share button in the game? I'll also take a look into that.

**Comment by Drezzz** [comment]
@Treholt3103 Yea, that's what I figured. The current plan is literally to just link the most up to date save from the host in discord literally every time we start.

@DominicMaas oh I guess it would sync forward. Will there be an issue when you get deeper into the game? I.e., random things happening in the city, etc.? I figured we'd pause it to try to ensure as close to a sync'd game as possible. Again, I have like... 10 minutes of play time in the game LOL. Thanks for looking into getting more than 2 people though! 

Also, I noticed deleting roads and stuff isn't sync'd yet. That's in the works I assume? You guys are actually so responsive its great!

**Comment by Treholt3103** [comment]
There should not be a problem with the way buildings are handled even as the city grow bigger, but do say if sometimes you expirience part of Roads not comming over.

Im looking into deletion of Roads, and also syncing of zones. It should not be a problem it just takes time :)

**Comment by Drezzz** [comment]
Okay cool. Also, my friend just reminded me that we're having an issue where zoning isn't being synced. Have you heard of this issue before? Thanks for the quick responses!

**Comment by Treholt3103** [comment]
Yeah the code for syncing zones ain't implemented yet :)

**Comment by Drezzz** [comment]
Aight. Thanks for the responses! Great work so far!

**Comment by DominicMaas** [comment]
Hey @Drezzz, could you redirect your workshop listing (maybe some text in the description) to the new official workshop listing here: https://steamcommunity.com/sharedfiles/filedetails/?id=1558438291

**Comment by Drezzz** [comment]
Sure! doing it now. Ill probably just close it in like a day or two.
