### ISSUE TITLE
Couldn't connect to server.

### ISSUE THREAD

**Issue by fitzydev** [CitiesSkylinesMultiplayer/CSM#5]
Hello,

I am currently having problems with connecting to friend's servers,

We have port forwarded everything as a precaution through UDP and TCP to be safe. 
It's not allowing them to connect to me and its not allowing me to connect to them.

We followed instructions accordingly, dlls are in the correct folders as far as I'm aware.

When we click "Manage Server" in game nothing pops up, and we cannot connect to each other's servers.

Just wondering if you have a fix for this or if this is an issue you know from experience! 

Thank you,

~ D-amp

**Comment by DominicMaas** [comment]
Hi,

I should probably make it clearer on the main page. This mod is still in heavy development and currently does not work. I'm currently laying down the foundational work in my free time to build the mod later.

Thanks,
Dominic

**Comment by saintflow47** [comment]
Hello Sir Dominic, is there any sort of rough estimated timeframe when you will start working on it? thanks!

**Comment by saintflow47** [comment]
Sounds awesome! Thanks for your reply!

I will be very happy with something that 'works' for the time being, if it means i can enjoy cities together with a friend when I put some effort into making it work! Thanks so much!

**Comment by luccaa456** [comment]
@DominicMaas do you have a estimated time for the mod start working ?

**Comment by VozDeOuro** [comment]
waiting the mod start working v(1.0)

**Comment by Breadabix** [comment]
Any idea when this will be working?

**Comment by DominicMaas** [comment]
For any future updates on this project, please follow #7
