### ISSUE TITLE
Zone and Road Syncing Issues

### ISSUE THREAD

**Issue by aturneruk** [CitiesSkylinesMultiplayer/CSM#55]
**Describe the bug**
Areas zoned by either the host or the client do not always sync up. The chat box shows errors but these are cut off. The same problem also occurs with roads created by either host or client not showing on the other end, with the same error shown in the chat box. A large number of these error messages appear in the chatbox when this issue occurs. 

**To Reproduce**
1. Start new game with same settings on client and host
2. Join game
3. Create zoned areas

**Screenshots**
Host: 
![screenshot 6](https://user-images.githubusercontent.com/2829581/48277799-99424900-e443-11e8-9ba8-3b692f5e4f07.png)

Client: 
![paul screen](https://user-images.githubusercontent.com/2829581/48277801-9cd5d000-e443-11e8-9cde-af2e0d85e2b5.png)

Errors shown on host:
![errors](https://user-images.githubusercontent.com/2829581/48277804-9f382a00-e443-11e8-8c6b-2452ed81bd66.JPG)

**Other Info**
We are not using any other mods or DLC, and are using stock C:S maps not from the DLCs. The connection is made over the internet rather than a local network.

**Comment by Treholt3103** [comment]
The problems ain't the zones, the problem is the roads, as you can see in the pictures not all roads have come over. When a road is created it creates the zones, when you are later changing zones, you are sending messages of changing some zone values that does not exist :)

**Comment by aturneruk** [comment]
Latest version from Azure/Github @DominicMaas 

Ahhh right so all of the issues come from the roads?

**Comment by Treholt3103** [comment]
Yes i believe the problem is not directly with the way the zones sync, but is a problem arising from creating zones on unsynced parts of roads :)
