### ISSUE TITLE
Manage Server 

### ISSUE THREAD

**Issue by unknownArkon2233** [CitiesSkylinesMultiplayer/CSM#6]
The manage server button does not work, I can create a server yet the manage server button will not work.

**Comment by DominicMaas** [comment]
The "Manage Server" button is currently not implemented. I'm going to start work on implementing it soon.

**Comment by unknownArkon2233** [comment]
how do we find out what port and ip we are using ?

**Comment by DominicMaas** [comment]
The default port is 4230 (this will be changeable in the future), you can find your local IP address (if connecting with LAN) by typing "ipconfig" into the command prompt. If you are connecting to a server over the internet, you can google "What's my IP" and google will tell you.

**Comment by unknownArkon2233** [comment]
Emm just a problem my friend cant connect to the server got no idea why is there a way for me to set my ip address instead of it being automatic

**Comment by DominicMaas** [comment]
AFAIK connecting to a server does not currently work (I think I was 90% ready, I'll take another look at it tomorrow).

**Comment by unknownArkon2233** [comment]
ahh ok cant wait

**Comment by DominicMaas** [comment]
I have just confirmed that local network connections now work. Just follow the instructions on the readme file and follow #7 for future updates.
