### ISSUE TITLE
Can't reconnect to savegame

### ISSUE THREAD

**Issue by Treholt3103** [CitiesSkylinesMultiplayer/CSM#68]
When i'm trying to load an earlier safe game by sharing the save game file, the client won't connect to the server.

The following error are shown on the debug display 
![error reconnection](https://user-images.githubusercontent.com/41299009/50229414-8e67c600-03aa-11e9-8c3b-9f980b401bb5.png)

**Comment by DominicMaas** [comment]
What does the text log look like?

**Comment by Treholt3103** [comment]
More testing results, somehow it's possible to join after having created a server, and then closed it however that results in a cascade of other problems, so it's not a fix

**Comment by DominicMaas** [comment]
So if player 1 creates a server and then closes it, player 2 can still connect?

**Comment by Treholt3103** [comment]
No player 1 and player 2 can both create servers then player 2 can close his server and join :)
