### ISSUE TITLE
Mod Timeline

### ISSUE THREAD

**Issue by dfence22** [CitiesSkylinesMultiplayer/CSM#7]
hey, i have few friends and myself interested in the Mod. We were just wondering how far along you were with implementing connections to servers and such. We did the basic install.  let us know if you need testers!

**Comment by DominicMaas** [comment]
The semester ends this week, so next week I'll try get a working prototype running, and sync basic resources between clients.

**Comment by dfence22** [comment]
Oh sweet. Understandable
Man. I just graduated. Good luck with finals a such

**Comment by DominicMaas** [comment]
Thanks! 

I'll spend this weekend working on getting basic connections working, the ability to send and receive chat messages (does not seem important, but a good way to test everything), track connected clients, ability to kick clients, and some server message support. (e.g xx Joined the Game). All groundwork for hopefully syncing resources, roads, buildings etc. in the future.

And to make it easier to install, I'm going to see if I can auto build the required files on commit, so you just have to download it from GitHub. (May also add in update notifications into the mod on startup, shouldn't be too difficult).

**Comment by pa9k** [comment]
Hey I just wanted to say that I appreciate the work you are putting into this and really look forward to trying this out one day.

**Comment by saintflow47** [comment]
Yeah man finally!!! Have been waiting so long for you to continue your work here :D

**Comment by AWL-Gaming** [comment]
Looking forward to trying this out. Thanks for all the effort you're putting in this!

**Comment by DominicMaas** [comment]
Progress Update: 

- There is now a `build.ps1` file under the `scripts` folder. This script automatically handles building and installing the mod (instructions on the readme page). 
- Continuous Integration is setup (automatically build the mod on every commit), these .zip files (with an install script) are automatically uploaded to Azure, although I have not setup a way to easily view them yet.
- Changed the networking library to something newer and more supported (so I could not work on more advanced networking stuff). At the same time I re-wrote the networking code, works much better now. I have also confirmed testing over the same PC and local network. Have not tested over internet yet.
- General clean up of the project so it's easier to understand.

Up Next:

- Server needs to keep track of clients and remove any clients that drop.
- Implement Manage Server page (will show all connected users).
- UPNP Support.
- Expose Azure storage files.
- Chat UI (will also display debug messages).
- Client/Server connected/disconnected messages in chat.

If anyone wants to test the current state of connecting and disconnecting, that would be awesome. Make sure you accept the firewall prompt, and port forward if testing over internet.

Easiest way to test is just have someone host the server, and have another person try connect to it. If successful, the status text should say "Connected". Once the chat UI is setup, you will be able to see the debug messages, making testing super easy.

**Comment by dfence22** [comment]
will be testing this sometime today or tonight. will let you know the findings

**Comment by dfence22** [comment]
friend is having trouble with powershell and visual studios, it wont allow him to "run with powershell"
 and tips?

**Comment by DominicMaas** [comment]
I can provide you with a pre built version. All you have to do is run the install.ps1 script ("run with power shell should work). You can also manually copy the DLLs if you know how to install mods.

The download is [here](https://gridentertainment.blob.core.windows.net/general-storage/csm/2018.162.3.zip). To get any version, you just have to look at the commits on this repository and hover over a green tick. This will say something like "Success 2018.162.3 succeeded". Simply replace VERSION_NUMBER with the version number you want in this url: `https://gridentertainment.blob.core.windows.net/general-storage/csm/VERSION_NUMBER.zip`

**Comment by Heremeus** [comment]
Hey dude,
just wanted to let you know your work is very much appreciated!
Let us know when you reach a point where you think external contributions would be helpful.

**Comment by Gensink** [comment]
How usable is this mod in its current state?

**Comment by DominicMaas** [comment]
You can currently connect to, and host a server. The current simulation speed is also synced. That's about it.

**Comment by kacperkor** [comment]
Hey, can you tell what's the current state of development?

**Comment by DominicMaas** [comment]
Sure, I've got semester break starting next week (for two weeks), so I'm planning to work on the mod then. Specifically fixing building the mod, improving the multiplayer UI to make more sense, implement pause syncing and start syncing resources.

**Comment by Sander0542** [comment]
Hi,

Is there any progress since the latest commit?

**Comment by DominicMaas** [comment]
I'll be updating the readme with more information shortly. Current progress can be seen on the readme file.
