### ISSUE TITLE
Installation question

### ISSUE THREAD

**Issue by dfence22** [CitiesSkylinesMultiplayer/CSM#8]
Hey, in your installation, it asks for the "steam folder directory" in power shell. does this mean the steamapps folder or the Local Appdata location of the original install?

EDIT: I think i figured it out, i used the explorer directory of the overall steam folder. sorry for the stupid question. IF that wasn't correct, i ask for some guidance, thanks!

**Comment by DominicMaas** [comment]
Yeah, just the root steam folder, I'll make it clearer in the script and readme page.
