### ISSUE TITLE
Cant Host Server

### ISSUE THREAD

**Issue by DetectiveMo** [CitiesSkylinesMultiplayer/CSM#9]
Hi,

I would like you to thank you for your amazing work. There is a Issue. I intalled the mod manually and Cities Skylines actually read it perfectly, the mod was suscesfully installed but there is a litte issue. I cannot host a servere, when I click on Host game it dosent do anything, but when I click join its works.

I would like to Host a game for me and my friend but it dosent do anything, can you help us.

Thank you for advance,

Greetings,

PS:Sorry for my bad english

**Comment by DominicMaas** [comment]
I have not added a debug log, so it's hard to tell what's happening. But there is a good chance that either your firewall is blocking the port, or you need to port forward your router (if hosting over the internet)

It should also be noted that the mod only currently supports connecting, hosting servers and syncing simulation speed. That's about it.

**Comment by DetectiveMo** [comment]
Hi,
Thank you for your respond, Is it possible to play LAN toegether, but do we have to host of can we just only click connect. Beacuse If we are on the same internet IP it is possible to only click  join game. Or do you have to still host a game.
I checked my firewall and its still givinv a problem, I think its my router, beacuse I dont have a port forwaard connection.

greetings

**Comment by DominicMaas** [comment]
If you are playing LAN, one person must host and the other will connect to it. In this case (as you are LAN), you do not need to port forward. 

On the computer you want to host from, type 'ipconfig' in the command prompt to find your IP address, this is the address that the client will connect to.

For example:
Your PC: Type 'ipconfig' find an IP Address of 192.168.0.1, host server.
Other PC: Click connect, type in '192.168.0.1' and it should connect to the server.

**Comment by DetectiveMo** [comment]
Oke,
If you click on host and nothing happends then you cant play (LAN) : (

**Comment by shubham-root** [comment]
I couldn't get the install script to run but copying the required files into the mod folder did the trick for me and the mod is now available to use. But as you mentioned in the issue #10 here, on using **ModTools** to debug for **Host Game**. Getting the error
`TypeLoadException: Could not load type`
`'System.Threading.CancellationTokenSource' from assembly System.Threading`
![photo6282913551022663769](https://user-images.githubusercontent.com/9352128/43679061-14be56d6-983c-11e8-8410-c40828d70810.jpg)

**Comment by DominicMaas** [comment]
@shubham-root Is there a `System.Threading` dll in the mod bin folder? (It should automatically be generated). I forgot to include this in the libs when updating the mod last.

**Comment by DominicMaas** [comment]
I updated the scripts a little while ago to take into account the new DLL, I've just updated the Continuious Integration (CI - see the readme file) to bundle this DLL into the zip folder. Easiest way to install the mod is now via the CI builds.

I'll also update the readme file with more information about hosting servers and connecting to them.
