### ISSUE TITLE
Toll booths/Relocate building

### ISSUE THREAD

**Issue by deadmonstor** [CitiesSkylinesMultiplayer/CSM#99]
**Describe the bug**
When moving toll booths it leaves the road behind making an infinite road that you cannot move. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Place down a toll road
2. Relocate building
3. Place down at another position
4. The roads would not have been removed and it will leave an infinite road 

**Expected behaviour**
Will not leave behind a road

**Comment by TeddJohnson** [comment]
I also had an issue with tollbooths. When I tried to delete one, it was stuck there as a mostly invisible  object.
